version: '0'

services:
  frontend_streamlit:
    build:
        dockerfile: frontend/Dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./frontend:/frontend_streamlit
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db/mydatabase
    depends_on:
      - triton_server
      - db
  
  triton_server:
    build:
        dockerfile: triton_models/Dockerfile
    volumes:
      - ./triton_models/models:/models
    ports:
      - 8200:8000 #HTTP requests
      - 8201:8001 #GRPC request
      - 8202:8002 # ROMETHEUS METRICS
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    runtime: nvidia

    command: ["tritonserver", "--model-repository=/models"]

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    # volumes:
    #   - ./database:/var/lib/postgresql/data


  