version: '3.8'

services:
  triton_server:
    build:
        dockerfile: ./Dockerfile
    volumes:
      - ./triton_server/triton_models/models:/models
    ports:
      - 8000:8000 #HTTP requests
      - 8001:8001 #GRPC request
      - 8002:8002 # ROMETHEUS METRICS
    command: ["tritonserver", "--model-repository=/models"]
  